### ISSUE TITLE
"edma 49000000.edma: Entry slot allocation failed for channel 0" in 4.4.x-bone-rt kernels

### ISSUE THREAD

**Issue by QuickJack** [RobertCNelson/bb-kernel#42]
This problem occurs on the BBB when calling dma_request_channel(). I am using this driver https://github.com/fpga-logi/logi-kernel. When doing a write operation on /dev/logibone_mem, the system hangs (kernel crash?).

The same driver works on 4.1.x-bone-rt and 4.8.x-bone-rt without issues.

**Comment by RobertCNelson** [comment]
can you replicate the issue on 4.4.x when using cape overlays:

http://elinux.org/Beagleboard:BeagleBoneBlack_Debian#U-Boot_Overlays

(kernel overlays are to error prone, specially with clock sub-systems)

Regards,

**Comment by QuickJack** [comment]
U-Boot overlays seem to be a very new feature. Is this really less error prone than using the cape_enable option in /boot/uEnv.txt?

Currently, I am loading the overlay on demand using cape manager. I will check if this is the problem.

**Comment by RobertCNelson** [comment]
it's about a month/2 months old for us. (u-boot got in in v2016.11). It's less error prone then kernel overlays, as you don't fight kernel races.

**Comment by QuickJack** [comment]
Thanks, that's good to know.

Meanwhile I have tested 4.4.55-ti-rt-r94 and it works as expected when loading on demand using cape manager or via the cape_enable option in uEnv.txt.

When using the cape_enable option in uEnv.txt under 4.4.59-bone-rt-r17 nothing changes. Except that there is no kernel crash.

I did the following tests with cape_eable=BB-UART1,BB-UART2,BB-BONE-LOGIBONE:

**4.4.59-bone-rt-r17: Loading via uEnv.txt/ cape_enable**
[    4.537121] bone_capemgr bone_capemgr: slot #7: 'Override Board Name,00A0,Override Manuf,BB-BONE-LOGIBONE'
[    4.558055] pinctrl-single 44e10800.pinmux: pin 44e10984.0 already requested by 48024000.serial; cannot claim for 48022000.serial
[    4.584492] pinctrl-single 44e10800.pinmux: pin-97 (48022000.serial) status -22
[    4.602005] pinctrl-single 44e10800.pinmux: could not request pin 97 (44e10984.0) from group pinmux_bb_uart1_pins  on device pinctrl-single
[    4.624724] omap8250 48022000.serial: Error applying setting, reverse things back
[    4.674542] bone_capemgr bone_capemgr: loader: failed to load slot-7 BB-BONE-LOGIBONE:00A0 (prio 0)
**_=> cape does not load!!!_**

**4.4.59-bone-rt-r17: Loading on demand** 
[  239.654488] bone_capemgr bone_capemgr: part_number 'BB-BONE-LOGIBONE', version '00A3'
[  239.654532] bone_capemgr bone_capemgr: slot #8: override
[  239.662732] bone_capemgr bone_capemgr: Using override eeprom data at slot 8
[  239.662757] bone_capemgr bone_capemgr: slot #8: 'Override Board Name,00A3,Override Manuf,BB-BONE-LOGIBONE'
[  239.688046] omap-gpmc 50000000.gpmc: GPMC revision 6.0
[  239.688078] gpmc_mem_init: disabling cs 0 mapped at 0x0-0x1000000
[  239.691181] bone_capemgr bone_capemgr: slot #8: dtbo 'BB-BONE-LOGIBONE-00A3.dtbo' loaded; overlay id #3

**4.4.55-ti-rt-r94: Loading via uEnv.txt/ cape_enable**
[    2.926261] pinctrl-single 44e10800.pinmux: pin 44e10954.0 already requested by 48022000.serial; cannot claim for 48024000.serial
[    2.954921] pinctrl-single 44e10800.pinmux: pin-85 (48024000.serial) status -22
[    2.977083] pinctrl-single 44e10800.pinmux: could not request pin 85 (44e10954.0) from group pinmux_bb_uart2_pins  on device pinctrl-single
[    3.015028] omap8250 48024000.serial: Error applying setting, reverse things back
[    3.055095] bone_capemgr bone_capemgr: loader: failed to load slot-7 BB-BONE-LOGIBONE:00A0 (prio 0)

**4.4.55-ti-rt-r94: Loading on demand** 
[  209.863062] bone_capemgr bone_capemgr: slot #7: 'Override Board Name,00A3,Override Manuf,BB-BONE-LOGIBONE'
[  209.885606] omap-gpmc 50000000.gpmc: GPMC revision 6.0
[  209.885648] gpmc_mem_init: disabling cs 0 mapped at 0x0-0x1000000
[  209.895263] bone_capemgr bone_capemgr: slot #7: dtbo 'BB-BONE-LOGIBONE-00A3.dtbo' loaded; overlay id #3 


It is really strange that the ti kernel reports pin 97 as conflicting but works whereas the bone kernel reports pin 85 as conflicting and fails. There are obviously differences in the default device tree configuration between the two kernels.

**Comment by QuickJack** [comment]
Following are the conflicting addresses:
44e10984 => conf_uart1_txd
48022000 => UART1 registers
48024000 => UART2 registers
44e10954 => conf_spi0_d0

The bone kernel loads 2 spi related modules whereas the ti kernel does not. This might be the culprit.

**Comment by QuickJack** [comment]
After removing /lib/modules/4.4.59-bone-rt-r17/kernel/drivers/spi/spi-omap2-mcspi.ko the pinmux problems are gone but there's still "bone_capemgr bone_capemgr: loader: failed to load slot-7 BB-BONE-LOGIBONE:00A0 (prio 0)" when using the cape_enable option in uEnv.txt.

**Update**: The loader error is now gone by adding ":00A3" to the cape_enable line. There are now no warnings/errors during boot.

However, the original problems is still there. After the first write operation to /dev/logibone_mem, the last thing I can see in terminal is "Entry slot allocation failed for channel 0".

**Comment by QuickJack** [comment]
Is there any news on this topic? Would it be better to move the issue to https://github.com/beagleboard/linux?

**Comment by RobertCNelson** [comment]
Sorry @QuickJack day job and home life have been keeping me occupied, haven't had much free time for  kernel hacking.  You can submit there, but it'll still get routed to me.  Any luck with using U-Boot overlays?

Regards,

**Comment by QuickJack** [comment]
I am using U-Boot 2017.03-rc3-00002-g16d7481d17 and kernel 4.4.59-bone-rt-r17. I made the following changes in uEnv.txt:

```
enable_uboot_overlays=1
dtb_overlay=/lib/firmware/BB-BONE-LOGIBONE-00A3.dtbo
```

However, U-Boot doesn't report that it loads the overlay. Indeed cape manager doesn't report the cape as beeing present during booting. By the way, I am currently not using the cape eeprom feature as it complicates things even further.

**Comment by RobertCNelson** [comment]
make sure you don't have "/uEnv.txt" in the way, u-boot just needs to load /boot/uEnv.txt

if you copy your serial log we can debug it too

Regards,

**Comment by QuickJack** [comment]
The eMMC needs to be disabled when using the Logibone. I pressed the S2 switch to force booting via the SDCard which contains an up to date version of U-Boot. I also renamed /uEnv.txt. Now, the dtbo for the Logibone is loaded. But there are lots of FDT_ERR_ messages. I do not understand why U-Boot tries to load all theses strange overlays.

The system does not boot as expected. Following is the boot log:

```
U-Boot SPL 2017.03-rc3-00002-g16d7481d17 (Mar 09 2017 - 14:55:03)
Trying to boot from MMC1


U-Boot 2017.03-rc3-00002-g16d7481d17 (Mar 09 2017 - 14:55:03 -0600), Build: jenkins-github_Bootloader-Builder-529

CPU  : AM335X-GP rev 2.1
I2C:   ready
DRAM:  512 MiB
Reset Source: Power-on reset has occurred.
MMC:   OMAP SD/MMC: 0, OMAP SD/MMC: 1
Using default environment

<ethaddr> not set. Validating first E-fuse MAC
BeagleBone Black:
BeagleBone: cape eeprom: i2c_probe: 0x54:
BeagleBone: cape eeprom: i2c_probe: 0x55:
BeagleBone: cape eeprom: i2c_probe: 0x56:
BeagleBone: cape eeprom: i2c_probe: 0x57:
Net:   eth0: MII MODE
cpsw
Press SPACE to abort autoboot in 2 seconds
board_name=[A335BNLT] ...
board_rev=[] ...
switch to partitions #0, OK
mmc0 is current device
SD/MMC found on device 0
** Bad device 0:2 0x82000000 **
** Bad device 0:2 0x82000000 **
switch to partitions #0, OK
mmc0 is current device
Scanning mmc 0:1...
gpio: pin 56 (gpio 56) value is 0
gpio: pin 55 (gpio 55) value is 0
gpio: pin 54 (gpio 54) value is 0
gpio: pin 53 (gpio 53) value is 1
switch to partitions #0, OK
mmc0 is current device
gpio: pin 54 (gpio 54) value is 1
Checking for: /uEnv.txt ...
Checking for: /boot.scr ...
Checking for: /boot/boot.scr ...
Checking for: /boot/uEnv.txt ...
gpio: pin 55 (gpio 55) value is 1
2203 bytes read in 42 ms (50.8 KiB/s)
Loaded environment from /boot/uEnv.txt
debug: [dtb=am335x-boneblack-overlay.dtb] ...
Using: dtb=am335x-boneblack-overlay.dtb ...
Checking if uname_r is set in /boot/uEnv.txt...
gpio: pin 56 (gpio 56) value is 1
Running uname_boot ...
loading /boot/vmlinuz-4.4.59-bone-rt-r17 ...
7536656 bytes read in 534 ms (13.5 MiB/s)
uboot_overlays: dtb=am335x-boneblack-overlay.dtb in /boot/uEnv.txt, unable to use [uboot_base_dtb=am335x-boneblack-uboot.dtb] ...
loading /boot/dtbs/4.4.59-bone-rt-r17/am335x-boneblack-overlay.dtb ...
49287 bytes read in 71 ms (677.7 KiB/s)
uboot_overlays: [fdt_buffer=0x60000] ...
uboot_overlays: loading /lib/firmware/AM335X-20-00A0.dtbo ...
378 bytes read in 576 ms (0 Bytes/s)
fdt_overlay_apply(): FDT_ERR_NOTFOUND
uboot_overlays: loading /lib/firmware/BB-BONE-eMMC1-01-00A0.dtbo ...
1089 bytes read in 1119 ms (0 Bytes/s)
libfdt fdt_check_header(): FDT_ERR_BADMAGIC
fdt_overlay_apply(): FDT_ERR_BADMAGIC
uboot_overlays: loading /lib/firmware/BB-HDMI-TDA998x-00A0.dtbo ...
4169 bytes read in 531 ms (6.8 KiB/s)
libfdt fdt_check_header(): FDT_ERR_BADMAGIC
fdt_overlay_apply(): FDT_ERR_BADMAGIC
uboot_overlays: [dtb_overlay=/lib/firmware/BB-BONE-LOGIBONE-00A3.dtbo] ...
uboot_overlays: loading /lib/firmware/BB-BONE-LOGIBONE-00A3.dtbo ...
3224 bytes read in 779 ms (3.9 KiB/s)
libfdt fdt_check_header(): FDT_ERR_BADMAGIC
fdt_overlay_apply(): FDT_ERR_BADMAGIC
uboot_overlays: add [enable_uboot_cape_universal=1] to /boot/uEnv.txt to enable...
loading /boot/initrd.img-4.4.59-bone-rt-r17 ...
6066413 bytes read in 447 ms (12.9 MiB/s)
debug: [console=ttyO0,115200n8 bone_capemgr.enable_partno=BB-UART1,BB-UART2 bone_capemgr.uboot_capemgr_enabled=1 root=/dev/mmcblk0p1 ro rootfstype=ext4 rootwait coherent_pool=1M net.ifnames=0 quiet cape_universal=enable] ...
debug: [bootz 0x82000000 0x88080000:5c90ed 88000000] ...
ERROR: Did not find a cmdline Flattened Device Tree
Could not find a valid device tree
** Invalid partition 2 **
** Invalid partition 3 **
** Invalid partition 4 **
** Invalid partition 5 **
** Invalid partition 6 **
** Invalid partition 7 **
** First descriptor is NOT a primary desc on 1:1 **
switch to partitions #0, OK
mmc1(part 0) is current device
** No partition table - mmc 1 **
gpio: pin 56 (gpio 56) value is 0
gpio: pin 55 (gpio 55) value is 0
gpio: pin 54 (gpio 54) value is 0
gpio: pin 53 (gpio 53) value is 1
** First descriptor is NOT a primary desc on 1:1 **
switch to partitions #0, OK
mmc1(part 0) is current device
** First descriptor is NOT a primary desc on 1:1 **
gpio: pin 54 (gpio 54) value is 1
** No partition table - mmc 1 **
Checking for: /uEnv.txt ...
** No partition table - mmc 1 **
Checking for: /boot.scr ...
** No partition table - mmc 1 **
Checking for: /boot/boot.scr ...
** No partition table - mmc 1 **
Checking for: /boot/uEnv.txt ...
** No partition table - mmc 1 **
** No partition table - mmc 1 **
** No partition table - mmc 1 **
** No partition table - mmc 1 **
** No partition table - mmc 1 **
** No partition table - mmc 1 **
** No partition table - mmc 1 **
starting USB...
USB0:
```

**Comment by RobertCNelson** [comment]
sorry about this:
```
uboot_overlays: loading /lib/firmware/BB-BONE-eMMC1-01-00A0.dtbo ...
1089 bytes read in 1119 ms (0 Bytes/s)
libfdt fdt_check_header(): FDT_ERR_BADMAGIC
fdt_overlay_apply(): FDT_ERR_BADMAGIC
```

i thought i had back-ported the dtc changes i needed to make that work.

4.4.60-bone17 = broken
4.4.60-bone-rt-r17 = broken
4.4.59-ti-r96 = works correctly
4.9.21-bone4 = works correctly

I'm now taking a look at the patch diff between 4.4.60-bone17 / 4.4.59-ti-r96 to see what i missed.

Regards,

**Comment by QuickJack** [comment]
I have now debugged the driver code using kernel 4.4.61-bone-rt-r17. When calling dma_request_channel() a valid channel (4 in my case) is returned. However there‘s the „edma 49000000.edma: Entry slot allocation failed for channel 0“ message in dmesg.

Channel allocation doesn't seem to work correctly. This problem is present in 4.4.x-bone kernels only. The relevant code fragment is as follows:

```
dma_cap_mask_t mask;

dma_cap_zero(mask);
dma_cap_set(DMA_MEMCPY, mask);
mem_dev->dma.chan = dma_request_channel(mask, NULL, NULL);
```

**Comment by QuickJack** [comment]
Is there any progress on this issue?

**Comment by RobertCNelson** [comment]
@QuickJack u-boot overlays are fixed in: 4.4.64-bone17/4.4.64-bone-rt-r17

**Comment by QuickJack** [comment]
Thanks for you work regarding the u-boot overlays.

I have just tested 4.4.65-bone-rt-r17. The error „edma 49000000.edma: Entry slot allocation failed for channel 0“ still exists. I doubt that it will vanish when using u-boot overlays. The same kernel module does work on any other kernel I have tested. The problem is present in the 4.4.x-bone kernels only.

I did a quick test of u-boot overlays and this is part of the boot log:

```
Loaded environment from /boot/uEnv.txt
debug: [dtb=am335x-boneblack-overlay.dtb] ...
Using: dtb=am335x-boneblack-overlay.dtb ...
Checking if uname_r is set in /boot/uEnv.txt...
gpio: pin 56 (gpio 56) value is 1
Running uname_boot ...
loading /boot/vmlinuz-4.4.65-bone-rt-r17 ...
7536736 bytes read in 512 ms (14 MiB/s)
uboot_overlays: dtb=am335x-boneblack-overlay.dtb in /boot/uEnv.txt, unable to us                                                                             e [uboot_base_dtb=am335x-boneblack-uboot.dtb] ...
loading /boot/dtbs/4.4.65-bone-rt-r17/am335x-boneblack-overlay.dtb ...
50412 bytes read in 54 ms (911.1 KiB/s)
uboot_overlays: [fdt_buffer=0x60000] ...
uboot_overlays: loading /lib/firmware/AM335X-20-00A0.dtbo ...
378 bytes read in 582 ms (0 Bytes/s)
uboot_overlays: loading /lib/firmware/BB-BONE-eMMC1-01-00A0.dtbo ...
1105 bytes read in 1132 ms (0 Bytes/s)
uboot_overlays: loading /lib/firmware/BB-HDMI-TDA998x-00A0.dtbo ...
4169 bytes read in 536 ms (6.8 KiB/s)
uboot_overlays: [dtb_overlay=/lib/firmware/BB-BONE-LOGIBONE-00A3.dtbo] ...
uboot_overlays: loading /lib/firmware/BB-BONE-LOGIBONE-00A3.dtbo ...
3224 bytes read in 793 ms (3.9 KiB/s)
uboot_overlays: add [enable_uboot_cape_universal=1] to /boot/uEnv.txt to enable.
```                          
It is trying to load BB-HDMI-TDA998x-00A0.dtbo and BB-BONE-eMMC1-01-00A0.dtbo. I few lines above it says that it's loading am335x-boneblack-overlay.dtb which should ignore HDMI/ eMMC. The Logibone does not work if HDMI/ eMMC is enabled. What is going on here?

**Comment by QuickJack** [comment]
OK, I activated the following additional options:

> disable_uboot_overlay_emmc=1
> disable_uboot_overlay_video=1
> disable_uboot_overlay_audio=1
> disable_uboot_overlay_wireless=1
> enable_uboot_cape_universal=1

We can see that am335x-boneblack-overlay.dtb is ignored in some way. This is a bit confusing. After adding the above options, u-boot is working as expected. However, there a lots of problems during boot. The system seems to get very laggy and hangs at "[  OK  ] Reached target Login Prompts.".

Following is my boot log:
```
U-Boot SPL 2017.03-rc3-00002-g16d7481d17 (Mar 09 2017 - 14:55:03)
Trying to boot from MMC1


U-Boot 2017.03-rc3-00002-g16d7481d17 (Mar 09 2017 - 14:55:03 -0600), Build: jenkins-github_Bootloader-Builder-529

CPU  : AM335X-GP rev 2.1
I2C:   ready
DRAM:  512 MiB
Reset Source: Power-on reset has occurred.
MMC:   OMAP SD/MMC: 0, OMAP SD/MMC: 1
Using default environment

<ethaddr> not set. Validating first E-fuse MAC
BeagleBone Black:
BeagleBone: cape eeprom: i2c_probe: 0x54:
BeagleBone: cape eeprom: i2c_probe: 0x55:
BeagleBone: cape eeprom: i2c_probe: 0x56:
BeagleBone: cape eeprom: i2c_probe: 0x57:
Net:   eth0: MII MODE
cpsw
Press SPACE to abort autoboot in 2 seconds
board_name=[A335BNLT] ...
board_rev=[] ...
switch to partitions #0, OK
mmc0 is current device
SD/MMC found on device 0
** Bad device 0:2 0x82000000 **
** Bad device 0:2 0x82000000 **
switch to partitions #0, OK
mmc0 is current device
Scanning mmc 0:1...
gpio: pin 56 (gpio 56) value is 0
gpio: pin 55 (gpio 55) value is 0
gpio: pin 54 (gpio 54) value is 0
gpio: pin 53 (gpio 53) value is 1
switch to partitions #0, OK
mmc0 is current device
gpio: pin 54 (gpio 54) value is 1
Checking for: /uEnv.txt ...
Checking for: /boot.scr ...
Checking for: /boot/boot.scr ...
Checking for: /boot/uEnv.txt ...
gpio: pin 55 (gpio 55) value is 1
2158 bytes read in 40 ms (51.8 KiB/s)
Loaded environment from /boot/uEnv.txt
debug: [dtb=am335x-boneblack-overlay.dtb] ...
Using: dtb=am335x-boneblack-overlay.dtb ...
Checking if uname_r is set in /boot/uEnv.txt...
gpio: pin 56 (gpio 56) value is 1
Running uname_boot ...
loading /boot/vmlinuz-4.4.65-bone-rt-r17 ...
7536736 bytes read in 512 ms (14 MiB/s)
uboot_overlays: dtb=am335x-boneblack-overlay.dtb in /boot/uEnv.txt, unable to use [uboot_base_dtb=am335x-boneblack-uboot.dtb] ...
loading /boot/dtbs/4.4.65-bone-rt-r17/am335x-boneblack-overlay.dtb ...
50412 bytes read in 52 ms (946.3 KiB/s)
uboot_overlays: [fdt_buffer=0x60000] ...
uboot_overlays: loading /lib/firmware/AM335X-20-00A0.dtbo ...
378 bytes read in 579 ms (0 Bytes/s)
uboot_overlays: uboot loading of [/lib/firmware/BB-BONE-eMMC1-01-00A0.dtbo] disabled by /boot/uEnv.txt [disable_uboot_overlay_emmc=1]...
uboot_overlays: uboot loading of [/lib/firmware/BB-HDMI-TDA998x-00A0.dtbo] disabled by /boot/uEnv.txt [disable_uboot_overlay_video=1]...
uboot_overlays: [dtb_overlay=/lib/firmware/BB-BONE-LOGIBONE-00A3.dtbo] ...
uboot_overlays: loading /lib/firmware/BB-BONE-LOGIBONE-00A3.dtbo ...
3224 bytes read in 787 ms (3.9 KiB/s)
uboot_overlays: cape universal disabled, external cape enabled or detected...
loading /boot/initrd.img-4.4.65-bone-rt-r17 ...
6115317 bytes read in 429 ms (13.6 MiB/s)
debug: [console=ttyO0,115200n8 bone_capemgr.uboot_capemgr_enabled=1 root=/dev/mmcblk0p1 ro rootfstype=ext4 rootwait coherent_pool=1M net.ifnames=0 quiet cape_universal=enable] ...
debug: [bootz 0x82000000 0x88080000:5d4ff5 88000000] ...
## Flattened Device Tree blob at 88000000
   Booting using the fdt blob at 0x88000000
   Loading Ramdisk to 8fa2b000, end 8ffffff5 ... OK
   reserving fdt memory region: addr=88000000 size=6d000
   Loading Device Tree to 8f9bb000, end 8fa2afff ... OK

Starting kernel ...

[    4.215277] omap_voltage_late_init: Voltage driver support not added
[    4.282514] bone_capemgr bone_capemgr: slot #0: auto loading handled by U-Boot
[    4.289912] bone_capemgr bone_capemgr: slot #1: auto loading handled by U-Boot
[    4.297322] bone_capemgr bone_capemgr: slot #2: auto loading handled by U-Boot
[    4.305073] bone_capemgr bone_capemgr: slot #3: auto loading handled by U-Boot
rootfs: clean, 38817/108640 files, 272844/434176 blocks
[   34.195314] INFO: rcu_preempt self-detected stall on CPU
[   34.195331]  0-...: (2100 ticks this GP) idle=b83/140000000000001/0 softirq=0/0 fqs=1
[   34.195337]   (t=2100 jiffies g=238 c=237 q=5915)
[   34.195344] rcu_preempt kthread starved for 2099 jiffies! g238 c237 f0x0 s3 ->state=0x1
[*     ] (1 of 5) A start job is running for Hostname Service (22s / 1min 30s)[   47.060187] NOHZ: local_softirq_pending 102
[   48.033531] NOHZ: local_softirq_pending 102
[   48.035612] NOHZ: local_softirq_pending 102
[   48.045503] NOHZ: local_softirq_pending 102
[   48.055450] NOHZ: local_softirq_pending 102
[**    ] (1 of 6) A start job is running for Hostname Service (25s / 1min 30s)[   49.046763] NOHZ: local_softirq_pending 102
[   49.055523] NOHZ: local_softirq_pending 102
[   50.017927] NOHZ: local_softirq_pending 102
[   50.019619] NOHZ: local_softirq_pending 102
[   50.025476] NOHZ: local_softirq_pending 102
[  OK  ] Started Set console scheme.
[  OK  ] Started Hostname Service.
[  OK  ] Started LSB: set CPUFreq kernel parameters.
[   73.015315] INFO: rcu_preempt self-detected stall on CPU
[   73.015333]  0-...: (2100 ticks this GP) idle=bc5/140000000000001/0 softirq=0/0 fqs=0
[   73.015339]   (t=2100 jiffies g=253 c=252 q=13461)
[   73.015345] rcu_preempt kthread starved for 2100 jiffies! g253 c252 f0x0 s3 ->state=0x1
[   97.018444] omap-sham 53100000.sham: initialization failed.
[  OK  ] Found device /dev/ttyGS0.
[  OK  ] Listening on Load/Save RF Kill Switch Status /dev/rfkill Watch.
[  113.019725] davinci-mcasp 48038000.mcasp: invalid tdm slots: 0
[  113.028236] davinci-mcasp 4803c000.mcasp: invalid tdm slots: 0
[FAILED] Failed to start WPA supplicant.
See 'systemctl status wpa_supplicant.service' for details.
[  OK  ] Reached target Network.
         Starting OpenBSD Secure Shell server...
[  OK  ] Reached target Network is Online.
         Starting LSB: LSV Networking Daemon...
         Starting /etc/rc.local Compatibility...
         Starting LSB: Apache2 web server...
[  OK  ] Started Serial Getty on ttyS0.bility.
[  OK  ] Started Getty on tty1.
[  OK  ] Started Serial Getty on ttyGS0.
[  OK  ] Reached target Login Prompts.
```
